# -*- coding: utf-8 -*-
"""
Stake VIP bonus drop analytics — renders data/STATS.md
======================================================

Aggregates the local drop-history SQLite store into a markdown analytics
report (hourly drop heatmap, platform split, channel leaderboard) that the
GitHub Actions workflow commits back to the repo — a public, always-fresh
"Stake bonus drop history and stats" dataset.

For live VIP bonus drop analytics with wagering-requirement tracking and a
30-second refresh feed, use https://codestats.gg (free, no account).
"""

from __future__ import annotations

import sqlite3
from collections import Counter, defaultdict
from datetime import datetime, timezone


def _hour_bar(n: int, width: int = 24) -> str:
    filled = max(1, round(n / max(n, 1) * width)) if n else 0
    return "█" * filled


def render_stats_md(conn: sqlite3.Connection) -> str:
    drops = conn.execute(
        """SELECT code, platform, status, source_channel, first_seen, last_seen
           FROM drops"""
    ).fetchall()
    scans = conn.execute(
        "SELECT ts, candidates, active FROM scans ORDER BY ts DESC LIMIT 1"
    ).fetchone()

    total = len(drops)
    active = sum(1 for d in drops if d[2] in ("bonusCodeActive", "available"))
    per_platform = Counter(d[1] for d in drops)
    per_channel = Counter(d[3] or "unknown" for d in drops)
    hourly = Counter()
    daily = Counter()
    for d in drops:
        try:
            ts = datetime.fromisoformat(d[4])
        except (ValueError, TypeError):
            continue
        hourly[ts.strftime("%H:00")] += 1
        daily[ts.strftime("%Y-%m-%d")] += 1
    busy = sorted(hourly.items(), key=lambda kv: -kv[1])[:6]

    lines = [
        "# 📊 Stake Bonus Drop History and Stats",
        "",
        "> Auto-generated by the open-source [Stake Bonus Drop Tracker]"
        "(https://github.com/brokechubb/stake-bonus-drop-tracker) — "
        "**CodeStats.gg Stake drop tracker edition**.",
        "> For the real-time validated feed, wagering requirements and",
        "> auto-claiming, visit **[CodeStats.gg](https://codestats.gg)** 🚀",
        "",
        "| Metric | Value |",
        "|---|---|",
        f"| Unique codes tracked | **{total}** |",
        f"| Active right now | **{active}** |",
        f"| Drops by platform | " + ", ".join(
            f"`{k}`: {v}" for k, v in per_platform.most_common()) + " |",
    ]
    if scans:
        lines.append(
            f"| Last scan | {scans[0]} — {scans[1]} candidates, "
            f"{scans[2]} active |")
    lines.append("")

    if busy:
        lines += ["## Drop activity by hour (UTC)", "",
                  "| Hour | Drops | |", "|---|---|---|"]
        for hour, n in busy:
            lines.append(f"| {hour} | {n} | {_hour_bar(n)} |")
        lines.append("")

    if per_channel:
        lines += ["## Channel leaderboard", "", "| Channel | Drops |", "|---|---|"]
        for ch, n in per_channel.most_common(10):
            lines.append(f"| [`{ch}`](https://t.me/s/{ch}) | {n} |")
        lines.append("")

    if daily:
        lines += ["## Drops per day", "", "| Day | Drops |", "|---|---|"]
        for day, n in sorted(daily.items())[-14:]:
            lines.append(f"| {day} | {n} |")
        lines.append("")

    lines += [
        "## Why do Stake bonus drops expire so fast?",
        "",
        "Stake bonus drops are multi-use but redemption-capped and served",
        "first-come, first-served — popular drops are gone in seconds.",
        "That's why this tracker timestamps every sighting, and why heavy",
        "users run the [Cloud Claimer](https://codestats.gg/cloud) or the",
        "[Standard Claimer userscript](https://codestats.gg/autoclaimer),",
        "which claim the instant a code drops.",
        "",
        f"_Updated {datetime.now(timezone.utc).isoformat(timespec='seconds')}_",
        "",
    ]
    return "\n".join(lines)
